/*
	Άγγελος Τζώρτζης
	ice18390094
*/

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "project_1.h"

int *ip_1_svc(arrays *argp, struct svc_req *rqstp)
{
	static int result;
	int i;

	result = 0;
	for (i = 0; i < argp->x.x_len; i++)
	{
		result += argp->x.x_val[i] * argp->y.y_val[i];
	}

	return &result;
}

output_2 *
a_1_svc(arrays *argp, struct svc_req *rqstp)
{
	static output_2 result;
	int i, sum1, sum2;
	float average1, average2;

	sum1 = 0;
	sum2 = 0;
	for (i = 0; i < argp->x.x_len; i++)
	{
		sum1 += argp->x.x_val[i];
		sum2 += argp->y.y_val[i];
	}

	average1 = (float)sum1 / argp->x.x_len;
	average2 = (float)sum2 / argp->y.y_len;

	result.out[0] = average1;
	result.out[1] = average2;

	return &result;
}

output_n *
p_1_svc(arrays_float *argp, struct svc_req *rqstp)
{
	static output_n result;
	int i;

	result.out.out_len = argp->x.x_len;
	result.out.out_val = (float *)malloc(sizeof(float) * argp->x.x_len);

	for (i = 0; i < argp->x.x_len; i++)
	{
		result.out.out_val[i] = argp->x.x_val[i] + argp->y.y_val[i];
		result.out.out_val[i] *= argp->r;
	}

	return &result;
}
