/*
	Άγγελος Τζώρτζης
	ice18390094
*/

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <unistd.h>
#include "project_1.h"

#define MAX_CLIENTS 5

void error(char *message)
{
	perror(message);
	exit(0);
}

int find_inner_product_1(char *host, int *array1, int *array2, int array_length)
{
	CLIENT *clnt;
	int i;
	int *result_1;
	arrays ip_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, FIND_INNER_PRODUCT, IP_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	ip_1_arg.x.x_len = array_length;
	ip_1_arg.y.y_len = array_length;
	ip_1_arg.x.x_val = (int *)malloc(sizeof(int) * array_length);
	ip_1_arg.y.y_val = (int *)malloc(sizeof(int) * array_length);

	for (i = 0; i < array_length; i++)
	{
		ip_1_arg.x.x_val[i] = array1[i];
		ip_1_arg.y.y_val[i] = array2[i];
	}

	result_1 = ip_1(&ip_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	return *result_1;
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

float *find_average_1(char *host, int *array1, int *array2, int array_length)
{
	CLIENT *clnt;
	int i;
	output_2 *result_1;
	arrays a_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, FIND_AVERAGE, A_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	a_1_arg.x.x_len = array_length;
	a_1_arg.y.y_len = array_length;
	a_1_arg.x.x_val = (int *)malloc(sizeof(int) * array_length);
	a_1_arg.y.y_val = (int *)malloc(sizeof(int) * array_length);

	for (i = 0; i < array_length; i++)
	{
		a_1_arg.x.x_val[i] = array1[i];
		a_1_arg.y.y_val[i] = array2[i];
	}

	result_1 = a_1(&a_1_arg, clnt);
	if (result_1 == (output_2 *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	return result_1->out;
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

float *find_product_1(char *host, float r, int *array1, int *array2, int array_length)
{
	CLIENT *clnt;
	int i;
	output_n *result_1;
	arrays_float p_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, FIND_PRODUCT, P_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	p_1_arg.x.x_len = array_length;
	p_1_arg.y.y_len = array_length;
	p_1_arg.x.x_val = (int *)malloc(sizeof(int) * array_length);
	p_1_arg.y.y_val = (int *)malloc(sizeof(int) * array_length);
	p_1_arg.r = r;

	for (i = 0; i < array_length; i++)
	{
		p_1_arg.x.x_val[i] = array1[i];
		p_1_arg.y.y_val[i] = array2[i];
	}

	result_1 = p_1(&p_1_arg, clnt);
	if (result_1 == (output_n *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	return result_1->out.out_val;

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;
	int socket_fd,
		newsocket_fd,
		port_number,
		client_length,
		choice, i,
		array_length,
		res1;
	struct sockaddr_in server_address, client_address;
	int *array_x, *array_y;
	float *res2, *res3, r;

	host = argv[1];

	// Check if we have the correct amount of arguments.
	if (argc != 2)
	{
		printf("Usage: %s server_host\n", argv[0]);
		fprintf(stderr, "Error, no port provided.\n");
		exit(1);
	}

	// Setting up the socket server.
	socket_fd = socket(AF_INET, SOCK_STREAM, 0);
	if (socket_fd < 0)
		error("Error opening socket!");

	bzero((char *)&server_address, sizeof(server_address));
	port_number = 9000; // Επιλογή θύρας σύνδεσης.
	server_address.sin_family = AF_INET;
	server_address.sin_port = htons(port_number);
	server_address.sin_addr.s_addr = INADDR_ANY;

	if (bind(socket_fd, (struct sockaddr *)&server_address, sizeof(server_address)) < 0)
		error("Error on binding.");

	// Number of clients that can connect to the server.
	listen(socket_fd, MAX_CLIENTS);

	while (1)
	{
		// Connect to new client every time.
		client_length = sizeof(client_address);
		printf("Waiting for a connection...\n");
		newsocket_fd = accept(socket_fd, (struct sockaddr *)&client_address, &client_length);
		if (newsocket_fd < 0)
			error("Error on accept.");

		if (fork() == 0)
		{
			close(socket_fd);
			printf("Connection accepted.\n");
			while (1)
			{
				// Receive the choice from the client.
				// This is inside the while loop so that the server can keep receiving choices from the client.
				recv(newsocket_fd, &choice, sizeof(choice), 0);

				switch (choice)
				{
				case 1:
					recv(newsocket_fd, &array_length, sizeof(array_length), 0);
					array_x = (int *)malloc(sizeof(int) * array_length);
					array_y = (int *)malloc(sizeof(int) * array_length);

					recv(newsocket_fd, array_x, sizeof(int) * array_length, 0);
					recv(newsocket_fd, array_y, sizeof(int) * array_length, 0);

					res1 = find_inner_product_1(host, array_x, array_y, array_length);
					send(newsocket_fd, &res1, sizeof(res1), 0);
					free(array_x);
					free(array_y);

					break;

				case 2:
					recv(newsocket_fd, &array_length, sizeof(array_length), 0);
					array_x = (int *)malloc(sizeof(int) * array_length);
					array_y = (int *)malloc(sizeof(int) * array_length);

					recv(newsocket_fd, array_x, sizeof(int) * array_length, 0);
					recv(newsocket_fd, array_y, sizeof(int) * array_length, 0);

					res2 = find_average_1(host, array_x, array_y, array_length);
					send(newsocket_fd, res2, sizeof(float) * array_length, 0);

					free(array_x);
					free(array_y);

					break;
				case 3:
					recv(newsocket_fd, &array_length, sizeof(array_length), 0);
					array_x = (int *)malloc(sizeof(int) * array_length);
					array_y = (int *)malloc(sizeof(int) * array_length);
					printf("Array length: %d\n", array_length);

					recv(newsocket_fd, &r, sizeof(r), 0);
					recv(newsocket_fd, array_x, sizeof(int) * array_length, 0);
					recv(newsocket_fd, array_y, sizeof(int) * array_length, 0);

					res3 = (float *)malloc(sizeof(float) * array_length);
					res3 = find_product_1(host, r, array_x, array_y, array_length);

					send(newsocket_fd, res3, sizeof(float) * array_length, 0);
					free(array_x);
					free(array_y);
					free(res3);

					break;
				case 4:
					exit(0);
					break;
				default:
					break;
				}
			}
			close(newsocket_fd);
			exit(0);
		}
		else
		{
			close(newsocket_fd);
		}
	}

	exit(0);
}
